{{ if and .Values.starrocksOperator.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-starrocks.name" . }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-starrocks.name" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ template  "operator.serviceAccountName" . }}
  namespace: {{ template  "operator.namespace" . }}
{{- end }}