{{- if .Values.starrocksOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.name" . }}-operator
  namespace: {{ template "operator.namespace" . }}
  labels:
    app: {{ template "operator.name" . }}-operator
  {{- if .Values.starrocksOperator.annotations }}
  annotations:
    {{- toYaml .Values.starrocksOperator.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "operator.name" . }}-operator
  replicas: {{ .Values.starrocksOperator.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      {{- if .Values.starrocksOperator.annotations }}
        {{- toYaml .Values.starrocksOperator.annotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "operator.name" . }}-operator
        version: {{ $.Chart.Version }}
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - /sroperator
        args:
        - --leader-elect
        {{- if .Values.starrocksOperator.watchNamespace }}
        - --namespace={{ .Values.starrocksOperator.watchNamespace }}
        {{- end }}
        env:
        - name: TZ
          value: {{ .Values.timeZone }}
        {{- if .Values.starrocksOperator.env }}
        {{- toYaml .Values.starrocksOperator.env | nindent 8 }}
        {{- end }}
        image: "{{ .Values.starrocksOperator.image.repository }}:{{ .Values.starrocksOperator.image.tag }}"
        imagePullPolicy: {{ .Values.starrocksOperator.imagePullPolicy }}
        name: manager
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          {{- toYaml .Values.starrocksOperator.resources | nindent 10 }}
      serviceAccountName: {{ template "operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.starrocksOperator.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.starrocksOperator.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.starrocksOperator.tolerations }}
      tolerations:
        {{- toYaml .Values.starrocksOperator.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
