{{- if and .Values.starrocksBeSpec .Values.starrocksBeSpec.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "starrockscluster.be.configmap.name" . }}
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "starrockscluster.name" . }}
    app: "be"
data:
{{ include "starrocksclster.be.config" . | indent 2 }}

{{- end }}

