{{- if and .Values.starrocksCluster.enabledCn .Values.starrocksCnSpec .Values.starrocksCnSpec.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "starrockscluster.cn.configmap.name" . }}
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "starrockscluster.name" . }}
    app: "cn"
data:
{{ include "starrockscluster.cn.config" . | indent 2 }}

{{- end }}
