apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "starrockscluster.fe.configmap.name" . }}
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "starrockscluster.name" . }}
    app: "fe"
data:
{{ include "starrockscluster.fe.config" . | indent 2 }}
